#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
from vboxtrayico.core import SystemTrayIcon
from PySide.QtGui import QWidget, QApplication

def main():
    app = QApplication(sys.argv)
    w = QWidget()
    trayIcon = SystemTrayIcon(w)
    trayIcon.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
